version: '3.8'

services:
  postgres:
    image: postgres:15  # Use the PostgreSQL version you want
    container_name: my_postgres_container
    restart: always
    environment:
      POSTGRES_USER: myuser          # Replace with your desired username
      POSTGRES_PASSWORD: mypassword  # Replace with your desired password
      POSTGRES_DB: mydatabase        # Replace with your desired database name
    ports:
      - "5432:5432"  # Expose port 5432 on the host
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Mount the volume to persist data

volumes:
  postgres_data:
    driver: local