-- Create "books" table
CREATE TABLE "books" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "title" character varying NOT NULL, "author" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "delete_time" timestamptz NULL, "age" bigint NOT NULL, "rank" double precision NULL, "active" boolean NOT NULL DEFAULT false, "password" character varying NOT NULL, "name" character varying NOT NULL, "url" jsonb NULL, "strings" jsonb NULL, "state" bigint NOT NULL DEFAULT 0, "uuid" uuid NOT NULL, PRIMARY KEY ("id"));
-- Create index "user_age_name" to table: "users"
CREATE UNIQUE INDEX "user_age_name" ON "users" ("age", "name");
-- Create index "users_name_key" to table: "users"
CREATE UNIQUE INDEX "users_name_key" ON "users" ("name");
-- Create "cards" table
CREATE TABLE "cards" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "card_no" character varying NOT NULL, "user_card" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "cards_users_card" FOREIGN KEY ("user_card") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
